import { MetadataRoute } from 'next';

/**
 * robots.txt — generated by Next.js at build time from this file.
 *
 * Allow everything user-facing; block:
 *   - /api/* (no value crawling our endpoints)
 *   - /admin/* (private staff area; URLs are tokenized but we still hide them)
 *   - /reservation/* (per-customer tokenized URLs sent by email)
 */

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/admin/', '/reservation/'],
      },
    ],
    sitemap: 'https://latinagrill.pt/sitemap.xml',
    host: 'https://latinagrill.pt',
  };
}
